# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Copy your Nginx configuration file to the container
#COPY nginx.conf /etc/nginx/nginx.conf

# Copy the server block configuration
COPY backend/dev/valhalla /etc/nginx/conf.d/default.conf


# Expose port 80 to allow external access
EXPOSE 80

# Start Nginx when the container launches
#CMD nginx
